Rails.application.routes.draw do
  get "/" => "launch#index"
  get "/index" => "launch#index"
  get "/launch" => "launch#index"
  get "/feature" => "launch#feature"
  get "/blog" => "launch#blog"
  get "/about" => "launch#about"
  get "/graph" => "launch#graph"
  get "/contact" => "launch#contact"
  get "/sentiment_fetch" => "launch#sentiment_fetch"
  get "/ticket_fetch" => "launch#ticket_fetch"
  get "/cs_fetch" => "launch#feature"
  get "/login/fcebook" => "login#facebook"
  get "/login" => "login#index"
end
